### PR TITLE
Convert to a maven project + Add PMD reporting

### PR DESCRIPTION
**Pull request by sigee**

### CODE REVIEW

**Comment by tuomount** [comment]
Is there a reason for converting Maven project? I personally would prefer Gradle but I haven't seen use for that yet.

This project should runnable with both Ubuntu 12.04 and 14.04 out of box without need of installing Oracle Java or compiling OpenJDK 1.8. Because of this sources needs to be java 1.7 compliant.

**Comment by sigee** [comment]
The reason: Maven can have a lot of plugins like PMD that helps to improve code quality.
You can run **mvn clean install** and the result is a JAR file
that is runable (everywhere)
that is tested (Eg. with JUnit or TestNG)
that is tested with PMD, CheckStyle
You can check your project easily with CI servers (Eg. Travis-CI)

Gradle can be an alternative solution.
Maven can run from JDK 1.5, so it is not problem if you want to use 1.7

**Comment by tuomount** [comment]
Okay, sounds good. Then it would be possible to do JUnits without actually include JUnit jar to project.
I would personally prefer Gradle over Maven but If you like more about Maven that's okay too. I could accept this pull request if Java version would be set to 1.7 or do you want to create a new pull request?

**Comment by sigee** [comment]
I'll fix this PR in 1 or 2 hours. ;)

**Comment by tuomount** [comment]
Let's try with maven!

**Pull request merged**
